// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlTpq0N7NXhoVGWkfU_DMt0GF3LBqNCjc',
    appId: '1:454627540836:web:8703d69cc211df1e94c471',
    messagingSenderId: '454627540836',
    projectId: 'poker-app-2c84f',
    authDomain: 'poker-app-2c84f.firebaseapp.com',
    storageBucket: 'poker-app-2c84f.firebasestorage.app',
    measurementId: 'G-NJ0TNCNJ5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOZCMZB6urrr1Z-C2uuST3sEe4IetffWM',
    appId: '1:454627540836:android:7070cf7f16cb824294c471',
    messagingSenderId: '454627540836',
    projectId: 'poker-app-2c84f',
    storageBucket: 'poker-app-2c84f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi_06rDGBPgabZskCPj4oyNRYtMiL6cos',
    appId: '1:454627540836:ios:d1e5692cb1fbdcda94c471',
    messagingSenderId: '454627540836',
    projectId: 'poker-app-2c84f',
    storageBucket: 'poker-app-2c84f.firebasestorage.app',
    iosBundleId: 'com.example.pokerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi_06rDGBPgabZskCPj4oyNRYtMiL6cos',
    appId: '1:454627540836:ios:d1e5692cb1fbdcda94c471',
    messagingSenderId: '454627540836',
    projectId: 'poker-app-2c84f',
    storageBucket: 'poker-app-2c84f.firebasestorage.app',
    iosBundleId: 'com.example.pokerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlTpq0N7NXhoVGWkfU_DMt0GF3LBqNCjc',
    appId: '1:454627540836:web:3c5c692eba8a2dbd94c471',
    messagingSenderId: '454627540836',
    projectId: 'poker-app-2c84f',
    authDomain: 'poker-app-2c84f.firebaseapp.com',
    storageBucket: 'poker-app-2c84f.firebasestorage.app',
    measurementId: 'G-X4MPS4K876',
  );
}
